# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29dcb3f3bba93d840ccd0f0f005ed4b488c4ce1c264d565bfd7a8d3cc198aed6b1fe8357955ee6ebfa434238df9883e5e84dd3def8268fffb9576a80245beb08

test:
  secret_key_base: e0ae726fed5921ff5b40865a99d5a5ff0727584cb1292f655cb1119d9096495c9cac372881352d1a948b4376704b0963afdb24db55abdb816c069fb402fc099c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
